### ISSUE TITLE
看上你的车了

### ISSUE THREAD

**Issue by sykiewang** [sen506/MySis001#1]
不知道该怎么开

**Comment by sen506** [comment]
@sykiewang  额。。按readme应该能理解才对啊=。=, 你是哪一步不懂？

**Comment by sykiewang** [comment]
mysql啊，我用过的都是下载到本地的 ，比如hardseed

**Comment by sen506** [comment]
@sykiewang 额。。这个工具其实只是把所有的sis001上面的所有页面信息爬下来而已, 方便自己进行本地搜索。。。。并不会把种子爬下来。。。搜索到相关的链接后需要自己进去那个链接把种子下下来。。。
